using System;
using System.Collections.Generic;
using System.Globalization;

internal static partial class Launcher
{
	internal static class Localization
	{
		public const string Korean = "ko";
		public const string English = "en";
		public static string CurrentLanguage = DetectDefaultLanguage();

		private static readonly Dictionary<string, string> KoreanTexts = new Dictionary<string, string>
		{
			{ "App.Title", "MineHarbor — Minecraft Server Launcher" },
			{ "Tooltip.Start", "선택한 프로필의 서버를 시작합니다. 단축키: F5" },
			{ "Tooltip.Stop", "월드를 저장하고 서버를 종료합니다. 단축키: Shift+F5" },
			{ "Tooltip.Settings", "서버 종류와 게임 설정을 변경합니다. 단축키: Ctrl+," },
			{ "Tooltip.LauncherUpdate", "지금 시점의 최신 런처를 새로 확인합니다." },
			{ "Tooltip.Update", "서버 실행 파일을 최신 호환 빌드로 갱신합니다." },
			{ "Tooltip.Console", "서버 로그와 명령 입력창을 열거나 닫습니다. 단축키: Ctrl+K" },
			{ "Tooltip.Servers", "프로필 관리와 멀티 서버 기능을 엽니다." },
			{ "Tooltip.Backup", "서버 전체를 백업하거나 복원합니다." },
			{ "Tooltip.Content", "호환 플러그인과 모드를 찾아 설치합니다." },
			{ "Tooltip.Players", "접속자와 권한·차단 목록을 관리합니다." },
			{ "Tooltip.Network", "접속 주소와 포트포워딩 상태를 확인합니다." },
			{ "Tooltip.Diagnostics", "개인정보를 가린 문제 진단 파일을 만듭니다." },
			{ "Tooltip.New", "새 서버 프로필을 만듭니다." },
			{ "Tooltip.Clone", "선택한 서버를 새 프로필로 복사합니다." },
			{ "Tooltip.Import", "기존 서버 폴더나 백업을 가져옵니다." },
			{ "Tooltip.Rename", "선택한 프로필 이름을 바꿉니다." },
			{ "Tooltip.Archive", "선택한 서버를 안전하게 보관합니다." },
			{ "Tooltip.SetActive", "선택한 프로필을 기본 서버로 사용합니다." },
			{ "Tooltip.Search", "입력한 이름으로 호환 항목을 검색합니다." },
			{ "Tooltip.Install", "선택한 항목과 필수 의존성을 설치합니다." },
			{ "Tooltip.OpenFolder", "플러그인 또는 모드 폴더를 엽니다." },
			{ "Tooltip.Save", "현재 설정을 저장합니다." },
			{ "Tooltip.Cancel", "변경하지 않고 닫습니다." },
			{ "Tooltip.Copy", "표시된 값을 클립보드에 복사합니다." },
			{ "Tooltip.Refresh", "현재 정보를 다시 불러옵니다." },
			{ "Tooltip.Recheck", "외부 접속 가능 여부를 다시 확인합니다." },
			{ "Tooltip.Router", "공유기 관리 페이지를 엽니다." },
			{ "Tooltip.Playit", "포트포워딩 대안 안내를 엽니다." },
			{ "Tooltip.Send", "입력한 서버 명령을 전송합니다." },
			{ "Tooltip.WhitelistAdd", "플레이어를 화이트리스트에 추가합니다." },
			{ "Tooltip.WhitelistRemove", "플레이어를 화이트리스트에서 제거합니다." },
			{ "Tooltip.GrantOp", "플레이어에게 OP 권한을 줍니다." },
			{ "Tooltip.RevokeOp", "플레이어의 OP 권한을 회수합니다." },
			{ "Tooltip.Kick", "플레이어를 서버에서 내보냅니다." },
			{ "Tooltip.Pardon", "플레이어의 접속 차단을 해제합니다." },
			{ "Tooltip.Ban", "플레이어의 서버 접속을 차단합니다." },
			{ "Tooltip.Browse", "파일을 선택합니다." },
			{ "Tooltip.Export", "선택한 백업을 다른 위치에 복사합니다." },
			{ "Tooltip.Theme", "화면 테마를 전환합니다." },
			{ "Tooltip.Language", "화면 언어를 전환합니다." },
			{ "Tooltip.Close", "이 창을 닫습니다." },
			{ "Tooltip.Later", "지금은 저장하지 않고 닫습니다." },
			{ "App.HeaderTitle", "내 MineHarbor 서버" },
			{ "App.Subtitle", "복잡한 설정 없이, 버튼 한 번으로 시작해 보세요" },
			{ "App.Error", "오류" },
			{ "Theme.Dark", "다크 모드" },
			{ "Theme.Light", "라이트 모드" },
			{ "Language.Changed", "언어를 한국어로 바꿨습니다." },
			{ "Status.Off", "서버 꺼짐" },
			{ "Status.Preparing", "서버 준비 중" },
			{ "Status.Error", "오류 발생" },
			{ "Status.Starting", "서버 시작 중" },
			{ "Status.Ready", "접속 준비 완료" },
			{ "Status.Stopping", "서버 종료 중" },
			{ "Address.Title", "친구에게 이 주소를 보내세요" },
			{ "Address.Empty", "서버를 시작하면 표시됩니다" },
			{ "Address.Copy", "복사" },
			{ "Address.Copied", "접속 주소를 복사했습니다." },
			{ "Button.Start", "서버 시작" },
			{ "Button.Stop", "서버 종료" },
			{ "Button.Settings", "설정" },
			{ "Button.Upgrade", "업데이트" },
			{ "Button.ConsoleOpen", "콘솔" },
			{ "Button.ConsoleClose", "콘솔 닫기" },
			{ "Button.Send", "전송" },
			{ "Button.Profiles", "서버 프로필" },
			{ "Button.MultiServer", "멀티 서버" },
			{ "Button.ServerManagement", "서버 관리" },
			{ "Button.Backup", "백업" },
			{ "Button.Content", "콘텐츠" },
			{ "Button.Schedules", "일정" },
			{ "Button.Dashboard", "대시보드" },
			{ "Button.Players", "플레이어" },
			{ "Button.Network", "네트워크" },
			{ "Button.Diagnostics", "진단" },
			{ "Button.LauncherUpdate", "런처 업데이트" },
			{ "Notice.LauncherLatest", "현재 최신 런처를 사용하고 있습니다." },
			{ "Notice.LauncherDeferred", "런처 업데이트를 나중으로 미뤘습니다." },
			{ "Main.ControlSection", "서버 제어" },
			{ "Main.ToolSection", "관리 도구" },
			{ "Console.Search", "콘솔 검색" },
			{ "Console.All", "전체" },
			{ "Console.Warning", "일반 경고" },
			{ "Console.Compatibility", "호환성" },
			{ "Console.Error", "오류" },
			{ "Console.Wrap", "줄 바꿈" },
			{ "Features", "호환 Java · 멀티 서버 · 전체 백업/복원 · Modrinth 콘텐츠 · UPnP 외부 접속 · 안전한 자동 OP" },
			{ "Notice.Ready", "서버를 열 준비가 되었어요." },
			{ "Notice.InitialSaved", "최초 설정을 저장했습니다. 서버 시작을 누르세요." },
			{ "Notice.InitialCanceled", "최초 설정은 서버를 시작할 때 다시 진행할 수 있습니다." },
			{ "Notice.SettingsFailed", "설정을 저장하지 못했습니다: {0}" },
			{ "Notice.CheckingFiles", "업데이트와 서버 파일을 확인하고 있습니다." },
			{ "Notice.StartFailed", "서버를 시작하지 못했습니다. 콘솔에서 오류를 확인해 주세요." },
			{ "Notice.StartCanceled", "서버 시작을 취소했습니다." },
			{ "Notice.ServerStopped", "서버가 종료되었습니다." },
			{ "Notice.ServerError", "서버가 오류로 종료되었습니다. 콘솔에서 원인을 확인해 주세요." },
			{ "Notice.WaitingServer", "서버가 접속을 받을 때까지 기다리고 있습니다." },
			{ "Notice.LocalReady", "로컬 접속이 준비됐습니다. 외부 접속을 확인하고 있습니다." },
			{ "Notice.Stopping", "월드를 안전하게 저장한 뒤 종료하고 있습니다." },
			{ "Notice.NoServer", "실행 중인 서버가 없습니다." },
			{ "Notice.StopBeforeSettings", "서버를 종료한 뒤 설정을 변경해 주세요." },
			{ "Notice.StopBeforeUpgrade", "서버를 종료한 뒤 업그레이드해 주세요." },
			{ "Notice.SettingsSaved", "서버 설정을 저장했습니다." },
			{ "Notice.SettingsCanceled", "설정 변경을 취소했습니다." },
			{ "Notice.UpgradeStarted", "서버 파일 업그레이드를 시작했습니다." },
			{ "Notice.UpgradeDone", "서버 파일 업그레이드를 완료했습니다." },
			{ "Notice.UpgradeFailed", "서버 파일 업그레이드를 완료하지 못했습니다: {0}" },
			{ "Notice.CloseAfterWork", "현재 작업이 끝난 뒤 런처를 닫습니다." },
			{ "Console.SetupCanceled", "서버 설정이 취소되었습니다." },
			{ "Console.LauncherError", "런처 오류: {0}" },
			{ "Thread.Start", "서버 시작 작업" },
			{ "Eula.Text", "Minecraft 서버를 실행하려면 Minecraft EULA에 동의해야 합니다.\r\n\r\n약관: https://aka.ms/MinecraftEULA\r\n\r\n약관을 읽었으며 동의하시겠습니까?" },
			{ "Eula.Title", "Minecraft EULA" },
			{ "Close.Question", "서버가 실행 중입니다. 안전하게 종료한 뒤 런처를 닫으시겠습니까?" },
			{ "Close.Title", "서버 종료" },
			{ "Setup.Title.New", "최초 서버 설정" },
			{ "Setup.Title.Edit", "서버 설정" },
			{ "Setup.Heading.New", "어떤 서버로 시작할까요?" },
			{ "Setup.Heading.Edit", "어떤 설정을 바꿀까요?" },
			{ "Setup.Description", "원하는 방식을 고르면 나머지는 알아서 준비해 드려요." },
			{ "Setup.Runtime", "서버 실행 파일" },
			{ "Setup.ProfileName", "서버 프로필 이름" },
			{ "Setup.ServerType", "서버 종류" },
			{ "Setup.MinecraftVersion", "Minecraft 버전" },
			{ "Setup.IncludeSnapshots", "스냅샷 포함" },
			{ "Setup.UseManualJar", "서버 JAR 직접 지정" },
			{ "Setup.BrowseJar", "찾기" },
			{ "Setup.JavaVersion", "JAR용 Java" },
			{ "Setup.Quick", "빠른 설정" },
			{ "Setup.Basic", "기본 정보" },
			{ "Setup.Rules", "서버 규칙" },
			{ "Setup.ServerName", "서버 이름을 알려주세요" },
			{ "Setup.MaxPlayers", "최대 인원" },
			{ "Setup.Port", "서버 포트" },
			{ "Setup.Memory", "서버 메모리" },
			{ "Setup.MemoryHint", "GB   권장 {0}GB · 시스템 {1}GB" },
			{ "Setup.GameMode", "게임 모드" },
			{ "Setup.Difficulty", "난이도" },
			{ "Setup.More", "더 세밀하게 설정하기" },
			{ "Setup.CloseMore", "세부 설정 닫기" },
			{ "Setup.Pvp", "PvP 허용" },
			{ "Setup.Whitelist", "화이트리스트 사용" },
			{ "Setup.CommandBlock", "명령 블록 허용" },
			{ "Setup.OnlineMode", "정품 계정 인증" },
			{ "Setup.PaperUpdate", "자동 업데이트" },
			{ "Setup.ViewDistance", "시야 거리" },
			{ "Setup.SimulationDistance", "시뮬레이션 거리" },
			{ "Setup.Owner", "서버 소유자" },
			{ "Setup.Cancel", "다음에" },
			{ "Setup.CancelEdit", "취소" },
			{ "Setup.Save", "이대로 저장" },
			{ "Setup.SaveEdit", "변경사항 저장" },
			{ "Setup.ValidationSummary", "표시된 입력값을 확인해 주세요." },
			{ "Setup.VersionLoading", "버전 목록 불러오는 중…" },
			{ "Setup.VersionReady", "버전 목록 준비 완료" },
			{ "Setup.VersionFallback", "네트워크 문제로 기본 목록 사용 중" },
			{ "Setup.ValidateTitle", "설정 확인" },
			{ "Setup.ServerNameRequired", "서버 이름을 입력해 주세요." },
			{ "Setup.OwnerInvalid", "서버 소유자 이름은 영문, 숫자, 밑줄을 사용해 3~16자로 입력해 주세요." },
			{ "Setup.ProfileInvalid", "서버 프로필 이름은 1~48자로 입력해 주세요." },
			{ "Setup.ManualJarMissing", "직접 지정할 .jar 파일을 선택해 주세요." },
			{ "Setup.SecurityTitle", "보안 경고" },
			{ "Setup.OnlineModeWarning", "정품 계정 인증을 끄면 다른 사람이 타인의 닉네임을 사칭할 수 있습니다. 그래도 끄시겠습니까?" },
			{ "Setup.CompatibilityTitle", "호환성 확인" },
			{ "Setup.CompatibilityWarning", "서버 종류나 Minecraft 버전을 바꾸면 기존 월드/플러그인/모드가 호환되지 않을 수 있습니다. 서버 시작 또는 업그레이드 전에 자동 백업을 만들고 계속합니다. 저장하시겠습니까?" },
			{ "Setup.WorldTitle", "기존 월드 확인" },
			{ "Setup.WorldWarning", "월드 유형 변경은 이미 생성된 월드에 적용되지 않습니다. 새 월드를 만들 때만 적용됩니다. 설정을 저장하시겠습니까?" },
			{ "Setup.DowngradeTitle", "월드 다운그레이드 차단" },
			{ "Setup.DowngradeWarning", "현재 월드는 더 최신 Minecraft 버전에서 열렸기 때문에 구버전으로 안전하게 내릴 수 없습니다. 기존 월드를 보호하기 위해 변경을 차단했습니다. 서버 프로필에서 새 서버를 만든 뒤 원하는 구버전을 선택해 주세요." },
			{ "Preset.Peaceful", "평화로움 야생" },
			{ "Preset.Easy", "쉬움 야생" },
			{ "Preset.Normal", "보통 야생" },
			{ "Preset.Hard", "어려움 야생" },
			{ "Preset.Hardcore", "하드코어 야생" },
			{ "Preset.CreativeNormal", "크리에이티브 월드\r\n일반 지형" },
			{ "Preset.CreativeFlat", "크리에이티브 월드\r\n평지" },
			{ "Preset.Custom", "직접 설정" },
			{ "GameMode.Survival", "서바이벌" },
			{ "GameMode.Creative", "크리에이티브" },
			{ "GameMode.Adventure", "모험" },
			{ "GameMode.Spectator", "관전자" },
			{ "Difficulty.Peaceful", "평화로움" },
			{ "Difficulty.Easy", "쉬움" },
			{ "Difficulty.Normal", "보통" },
			{ "Difficulty.Hard", "어려움" },
			{ "Hardcore", "하드코어" }
		};

		private static readonly Dictionary<string, string> EnglishTexts = new Dictionary<string, string>
		{
			{ "App.Title", "MineHarbor — Minecraft Server Launcher" },
			{ "Tooltip.Start", "Start the selected server profile. Shortcut: F5" },
			{ "Tooltip.Stop", "Save the world and stop the server. Shortcut: Shift+F5" },
			{ "Tooltip.Settings", "Change the server type and game settings. Shortcut: Ctrl+," },
			{ "Tooltip.LauncherUpdate", "Check for the latest launcher again right now." },
			{ "Tooltip.Update", "Update the server file to the latest compatible build." },
			{ "Tooltip.Console", "Open or close server logs and command input. Shortcut: Ctrl+K" },
			{ "Tooltip.Servers", "Open profiles and multi-server tools." },
			{ "Tooltip.Backup", "Back up or restore the complete server." },
			{ "Tooltip.Content", "Find and install compatible plugins or mods." },
			{ "Tooltip.Players", "Manage players, permissions, and bans." },
			{ "Tooltip.Network", "Check addresses and port forwarding." },
			{ "Tooltip.Diagnostics", "Create a privacy-redacted diagnostic bundle." },
			{ "Tooltip.New", "Create a new server profile." },
			{ "Tooltip.Clone", "Copy the selected server into a new profile." },
			{ "Tooltip.Import", "Import an existing server folder or backup." },
			{ "Tooltip.Rename", "Rename the selected profile." },
			{ "Tooltip.Archive", "Safely archive the selected server." },
			{ "Tooltip.SetActive", "Use the selected profile as the default server." },
			{ "Tooltip.Search", "Search compatible content by name." },
			{ "Tooltip.Install", "Install the selected item and required dependencies." },
			{ "Tooltip.OpenFolder", "Open the plugin or mod folder." },
			{ "Tooltip.Save", "Save the current settings." },
			{ "Tooltip.Cancel", "Close without saving changes." },
			{ "Tooltip.Copy", "Copy the displayed value to the clipboard." },
			{ "Tooltip.Refresh", "Refresh the current information." },
			{ "Tooltip.Recheck", "Recheck external reachability." },
			{ "Tooltip.Router", "Open the router administration page." },
			{ "Tooltip.Playit", "Open the port-forwarding alternative guide." },
			{ "Tooltip.Send", "Send the entered server command." },
			{ "Tooltip.WhitelistAdd", "Add the player to the whitelist." },
			{ "Tooltip.WhitelistRemove", "Remove the player from the whitelist." },
			{ "Tooltip.GrantOp", "Grant operator permission to the player." },
			{ "Tooltip.RevokeOp", "Revoke operator permission from the player." },
			{ "Tooltip.Kick", "Kick the player from the server." },
			{ "Tooltip.Pardon", "Remove the player's ban." },
			{ "Tooltip.Ban", "Ban the player from the server." },
			{ "Tooltip.Browse", "Choose a file." },
			{ "Tooltip.Export", "Copy the selected backup to another location." },
			{ "Tooltip.Theme", "Switch the interface theme." },
			{ "Tooltip.Language", "Switch the interface language." },
			{ "Tooltip.Close", "Close this window." },
			{ "Tooltip.Later", "Close without saving for now." },
			{ "App.HeaderTitle", "My MineHarbor Server" },
			{ "App.Subtitle", "Start your server with one button, without the setup noise." },
			{ "App.Error", "Error" },
			{ "Theme.Dark", "Dark mode" },
			{ "Theme.Light", "Light mode" },
			{ "Language.Changed", "Language changed to English." },
			{ "Status.Off", "Server off" },
			{ "Status.Preparing", "Preparing server" },
			{ "Status.Error", "Error" },
			{ "Status.Starting", "Starting server" },
			{ "Status.Ready", "Ready to join" },
			{ "Status.Stopping", "Stopping server" },
			{ "Address.Title", "Send this address to your friends" },
			{ "Address.Empty", "Shown after the server starts" },
			{ "Address.Copy", "Copy" },
			{ "Address.Copied", "Connection address copied." },
			{ "Button.Start", "Start" },
			{ "Button.Stop", "Stop" },
			{ "Button.Settings", "Settings" },
			{ "Button.Upgrade", "Update" },
			{ "Button.ConsoleOpen", "Console" },
			{ "Button.ConsoleClose", "Close console" },
			{ "Button.Send", "Send" },
			{ "Button.Profiles", "Profiles" },
			{ "Button.MultiServer", "Multi-server" },
			{ "Button.ServerManagement", "Servers" },
			{ "Button.Backup", "Backups" },
			{ "Button.Content", "Content" },
			{ "Button.Schedules", "Schedules" },
			{ "Button.Dashboard", "Dashboard" },
			{ "Button.Players", "Players" },
			{ "Button.Network", "Network" },
			{ "Button.Diagnostics", "Diagnose" },
			{ "Button.LauncherUpdate", "Launcher update" },
			{ "Notice.LauncherLatest", "You are using the latest launcher." },
			{ "Notice.LauncherDeferred", "Launcher update postponed." },
			{ "Main.ControlSection", "Server controls" },
			{ "Main.ToolSection", "Management tools" },
			{ "Console.Search", "Search console" },
			{ "Console.All", "All" },
			{ "Console.Warning", "Warnings" },
			{ "Console.Compatibility", "Compatibility" },
			{ "Console.Error", "Errors" },
			{ "Console.Wrap", "Word wrap" },
			{ "Features", "Compatible Java · multi-server · full backup/restore · Modrinth content · UPnP external access · safe owner auto-OP" },
			{ "Notice.Ready", "Ready to open your server." },
			{ "Notice.InitialSaved", "Initial setup saved. Press Start server." },
			{ "Notice.InitialCanceled", "Initial setup will run again when you start the server." },
			{ "Notice.SettingsFailed", "Could not save settings: {0}" },
			{ "Notice.CheckingFiles", "Checking updates and server files." },
			{ "Notice.StartFailed", "Could not start the server. Check the console for details." },
			{ "Notice.StartCanceled", "Server start was canceled." },
			{ "Notice.ServerStopped", "Server stopped." },
			{ "Notice.ServerError", "Server stopped with an error. Check the console for details." },
			{ "Notice.WaitingServer", "Waiting until the server accepts connections." },
			{ "Notice.LocalReady", "Local connection is ready. Checking external access." },
			{ "Notice.Stopping", "Saving the world safely before stopping." },
			{ "Notice.NoServer", "No server is running." },
			{ "Notice.StopBeforeSettings", "Stop the server before changing settings." },
			{ "Notice.StopBeforeUpgrade", "Stop the server before upgrading files." },
			{ "Notice.SettingsSaved", "Server settings saved." },
			{ "Notice.SettingsCanceled", "Settings change canceled." },
			{ "Notice.UpgradeStarted", "Server file upgrade started." },
			{ "Notice.UpgradeDone", "Server file upgrade completed." },
			{ "Notice.UpgradeFailed", "Could not complete server file upgrade: {0}" },
			{ "Notice.CloseAfterWork", "The launcher will close after the current task finishes." },
			{ "Console.SetupCanceled", "Server setup was canceled." },
			{ "Console.LauncherError", "Launcher error: {0}" },
			{ "Thread.Start", "Server start task" },
			{ "Eula.Text", "To run a Minecraft server, you must agree to the Minecraft EULA.\r\n\r\nTerms: https://aka.ms/MinecraftEULA\r\n\r\nHave you read and agreed to the terms?" },
			{ "Eula.Title", "Minecraft EULA" },
			{ "Close.Question", "The server is running. Stop it safely before closing the launcher?" },
			{ "Close.Title", "Stop server" },
			{ "Setup.Title.New", "Initial server setup" },
			{ "Setup.Title.Edit", "Server settings" },
			{ "Setup.Heading.New", "What kind of server should we start?" },
			{ "Setup.Heading.Edit", "Which settings should we change?" },
			{ "Setup.Description", "Pick a preset and the launcher will handle the rest." },
			{ "Setup.Runtime", "Server executable" },
			{ "Setup.ProfileName", "Server profile name" },
			{ "Setup.ServerType", "Server type" },
			{ "Setup.MinecraftVersion", "Minecraft version" },
			{ "Setup.IncludeSnapshots", "Snapshots" },
			{ "Setup.UseManualJar", "Use a custom server JAR" },
			{ "Setup.BrowseJar", "Browse" },
			{ "Setup.JavaVersion", "JAR Java" },
			{ "Setup.Quick", "Quick setup" },
			{ "Setup.Basic", "Basic info" },
			{ "Setup.Rules", "Server rules" },
			{ "Setup.ServerName", "Server name" },
			{ "Setup.MaxPlayers", "Max players" },
			{ "Setup.Port", "Server port" },
			{ "Setup.Memory", "Server memory" },
			{ "Setup.MemoryHint", "GB   Recommended {0}GB · System {1}GB" },
			{ "Setup.GameMode", "Game mode" },
			{ "Setup.Difficulty", "Difficulty" },
			{ "Setup.More", "More settings" },
			{ "Setup.CloseMore", "Hide details" },
			{ "Setup.Pvp", "Allow PvP" },
			{ "Setup.Whitelist", "Use whitelist" },
			{ "Setup.CommandBlock", "Allow command blocks" },
			{ "Setup.OnlineMode", "Online authentication" },
			{ "Setup.PaperUpdate", "Auto update" },
			{ "Setup.ViewDistance", "View distance" },
			{ "Setup.SimulationDistance", "Simulation distance" },
			{ "Setup.Owner", "Server owner" },
			{ "Setup.Cancel", "Later" },
			{ "Setup.CancelEdit", "Cancel" },
			{ "Setup.Save", "Save" },
			{ "Setup.SaveEdit", "Save changes" },
			{ "Setup.ValidationSummary", "Review the highlighted field." },
			{ "Setup.VersionLoading", "Loading version list…" },
			{ "Setup.VersionReady", "Version list ready" },
			{ "Setup.VersionFallback", "Using the built-in list because the network is unavailable" },
			{ "Setup.ValidateTitle", "Check settings" },
			{ "Setup.ServerNameRequired", "Enter a server name." },
			{ "Setup.OwnerInvalid", "Server owner must be 3-16 characters using letters, numbers, and underscores." },
			{ "Setup.ProfileInvalid", "Enter a server profile name between 1 and 48 characters." },
			{ "Setup.ManualJarMissing", "Select a .jar file to use as the server executable." },
			{ "Setup.SecurityTitle", "Security warning" },
			{ "Setup.OnlineModeWarning", "Disabling online authentication allows nickname impersonation. Continue anyway?" },
			{ "Setup.CompatibilityTitle", "Compatibility check" },
			{ "Setup.CompatibilityWarning", "Changing the server type or Minecraft version can break existing worlds, plugins, or mods. The launcher will create a backup before start or upgrade. Save anyway?" },
			{ "Setup.WorldTitle", "Existing world check" },
			{ "Setup.WorldWarning", "Changing the world type does not affect an existing world. It only applies to newly generated worlds. Save anyway?" },
			{ "Setup.DowngradeTitle", "World downgrade blocked" },
			{ "Setup.DowngradeWarning", "This world was opened by a newer Minecraft version and cannot be downgraded safely. The change was blocked to protect the world. Create a new server profile and choose the older version there." },
			{ "Preset.Peaceful", "Peaceful survival" },
			{ "Preset.Easy", "Easy survival" },
			{ "Preset.Normal", "Normal survival" },
			{ "Preset.Hard", "Hard survival" },
			{ "Preset.Hardcore", "Hardcore survival" },
			{ "Preset.CreativeNormal", "Creative world\r\nNormal terrain" },
			{ "Preset.CreativeFlat", "Creative world\r\nFlat" },
			{ "Preset.Custom", "Custom" },
			{ "GameMode.Survival", "Survival" },
			{ "GameMode.Creative", "Creative" },
			{ "GameMode.Adventure", "Adventure" },
			{ "GameMode.Spectator", "Spectator" },
			{ "Difficulty.Peaceful", "Peaceful" },
			{ "Difficulty.Easy", "Easy" },
			{ "Difficulty.Normal", "Normal" },
			{ "Difficulty.Hard", "Hard" },
			{ "Hardcore", "Hardcore" }
		};

		public static string DetectDefaultLanguage()
		{
			try
			{
				return string.Equals(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName, Korean, StringComparison.OrdinalIgnoreCase) ? Korean : English;
			}
			catch
			{
				return Korean;
			}
		}

		public static string NormalizeLanguage(string value)
		{
			return string.Equals(value, English, StringComparison.OrdinalIgnoreCase) ? English : Korean;
		}

		public static string ToggleLanguage()
		{
			CurrentLanguage = string.Equals(CurrentLanguage, Korean, StringComparison.OrdinalIgnoreCase) ? English : Korean;
			return CurrentLanguage;
		}

		public static string LanguageButtonText()
		{
			return string.Equals(CurrentLanguage, Korean, StringComparison.OrdinalIgnoreCase) ? "English" : "한국어";
		}

		public static string T(string key)
		{
			Dictionary<string, string> source = string.Equals(CurrentLanguage, Korean, StringComparison.OrdinalIgnoreCase) ? KoreanTexts : EnglishTexts;
			string value;
			if (source.TryGetValue(key, out value))
			{
				return value;
			}
			if (KoreanTexts.TryGetValue(key, out value))
			{
				return value;
			}
			return key;
		}

		public static string F(string key, params object[] args)
		{
			return string.Format(CultureInfo.CurrentCulture, T(key), args);
		}
	}
}
